### ISSUE TITLE
don't hardcode anything :)

### ISSUE THREAD

**Issue by davkhech** [Ngalstyan4/princeton-cas#1]
https://github.com/Ngalstyan4/princeton-cas/blob/6367d769dcd1dac081a30ca288fe047ba499dd08/Auth.js#L40

**Comment by Ngalstyan4** [comment]
Ապեր թեստինգի համարա զուտ, լուրջ բան չի .ՃՃ
թիմերից մեկն էլ նոդ էր օգտագործում խնդրեցին որ էս կոդը ուղարկեմ, դրա համար եմ գցել ստեղ
